name: Static Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and push to static repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
      - run: |
          npm i -g xdocs
          npm i -g sass
          git clone https://github.com/tsil-ukr/website-static .будування
          bash згенерувати.sh
          cd .будування
          git config user.name kohutd
          git config user.email davyd.kohut@gmail.com
          git add .
          git commit -m "🧬"
          git push